inbound-transport:
  - [http, 0.0.0.0, 8021]
  - [ws, 0.0.0.0, 8023]
outbound-transport: http
endpoint: http://localhost:80
admin: [0.0.0.0, 8024]
admin-api-key: my-api-pass
wallet-type: indy
wallet-name: my-wallet
wallet-key: my-wallet-pass
replace-public-did: true
preserve-exchange-records: true
auto-provision: true
seed: 000000000000000000000000000000X1
genesis-file: genesis.json
label: my-label
log-level: info
auto-ping-connection: true
auto-respond-messages: true
auto-accept-invites: true
auto-accept-requests: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-verify-presentation: true
auto-respond-presentation-request: true
auto-respond-presentation-proposal: true